name: Integration tests

on:
  push:
    branches: [ development, main, feat/* ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.6
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.6
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Integration Tests - new testnet
        run: cd scripts && /bin/bash local-testnet.sh new

      - name: Integration Tests - start testnet
        run: cd scripts && /bin/bash local-testnet.sh start

      - name: IntegrationTests - run tests
        run: cd scripts && ./bin/bash shard-meta-tests.sh

      - name: Integration Tests - stop testnet
        run: cd scripts && /bin/bash local-testnet.sh stop
